language: "ruby"

rvm:
  - "2.3.0"
  - "2.6.0"

sudo: false

install:
  - bundle install --retry=3

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 295b5bc78577b6eeeab5c7ee9b6adfda8c77b46bb9dccf876b299d8e0edecbaf

after_success:
  - bundle exec codeclimate-test-reporter
