/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Pokemon {
  species_id: string;
  exp: number;
  gender: "male" | "female" | "neuter";
  ability_id: string;
  item_id?: string | null;
  nature_id: string;
  hp: number;
  friendship: number;
  original_trainer?: string | null;
  ev: EvStats;
  iv: IvStats;
  primary_status_condition?: "poison" | "badly_poisoned" | "paralysis" | "sleep" | "freeze" | "burn" | null;
  wild?: boolean | null;
  moves: {
    move_id: string;
    pp: number;
    max_pp: number;
  }[];
  amie?: {
    [k: string]: any;
  } | null;
  growth_events?: {
    name: string;
    options: {
      [k: string]: any;
    };
  }[];
}
export interface EvStats {
  hp: number;
  atk: number;
  def: number;
  sp_atk: number;
  sp_def: number;
  speed: number;
}
export interface IvStats {
  hp: number;
  atk: number;
  def: number;
  sp_atk: number;
  sp_def: number;
  speed: number;
}
